### ISSUE TITLE
SDK error grpc._channel._InactiveRpcError:

### ISSUE THREAD

**Issue by FabienDanieau** [pollen-robotics/reachy2021-unity-package#23]
An error like this happens if the latest SDK version is used.

```
(reachy) >python reachy2021-unity-package-helloworld.py
Traceback (most recent call last):
  File reachy2021-unity-package-helloworld.py", line 93, in <module>
    say_hello()
  File "reachy2021-unity-package-helloworld.py", line 77, in say_hello
    reachy.head.look_at(0.5, -0.3, -0.1, duration=1.0)
  File "\reachy-sdk\reachy_sdk\head.py", line 188, in look_at
    goal_positions=self._look_at(x, y, z),
  File "\reachy-sdk\reachy_sdk\head.py", line 198, in _look_at
    neckik = self.inverse_kinematics(q)
  File "\reachy-sdk\reachy_sdk\head.py", line 135, in inverse_kinematics
    resp = self._kin_stub.ComputeHeadIK(req)
  File "\.conda\envs\reachy\lib\site-packages\grpc\_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File \.conda\envs\reachy\lib\site-packages\grpc\_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = ""
        debug_error_string = "{"created":"@1682412213.198000000","description":"Error received from peer ipv6:[::1]:50055","file":"src/core/lib/surface/call.cc","file_line":953,"grpc_message":"","grpc_status":12}"
 ```

**Comment by FabienDanieau** [comment]
As a workaround using the v0.5.4 solves the problem: https://github.com/pollen-robotics/reachy-sdk/releases/tag/v0.5.4
